include $(CLEAR_VARS)

MODULE:= $(TARGET_MODULE)

LOCAL_CFLAGS:= -D_REENTRANT -D_REENTRANT -lpthread -lm

LOCAL_SRC_FILES:= $(MODULE).c 
LOCAL_STATIC_LIBRARIES:= libmicro
LOCAL_MODULE:= bench_$(MODULE)
LOCAL_MODULE_TAGS := optional

include $(BUILD_EXECUTABLE)

